title: Competition and Consumer Commission of Singapore
url: https://www.cccs.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#4a90e2"
  secondary-color: "#f5a623"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: The Competition Commission of Singapore (“CCS”) was established on
  1 January 2005 to administer and enforce the Competition Act (the “Act”) 2004.
  On 1 April 2018, CCS was renamed the Competition and Consumer Commission of
  Singapore (“CCCS”) and took on an additional function of administering the
  Consumer Protection (Fair Trading) Act 2003. In relation to the Act, besides
  investigating and enforcing against practices that have an adverse effect on
  competition in Singapore, CCCS also represents Singapore in respect of
  competition matters and consumer protection matters in the international
  arena. In addition, CCCS has a statutory duty to advise the government, any
  public authority or any consumer protection organisation on national needs and
  policies in respect of competition matters and consumer protection matters
  generally.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dq5a8ww0lg01g.amplifyapp.com
prod: https://master.dq5a8ww0lg01g.amplifyapp.com
facebook-pixel: ""
shareicon: /images/cccs_logo.png
is_government: false
google_analytics_ga4: G-QPKZTNCQR1
linkedin-insights: ""
resources_name: media-and-consultation
